### ISSUE TITLE
Recommedation / Feature Request

### ISSUE THREAD

**Issue by gruvin** [Peaches491/OctoPrint-Touchtest#12]
Thanks for the plugin. Saved me a decent amount of time learning how to write them. :-)

Feature request: Lift tool before moving to next point. Lift height and Z touch height would be nice to include in plugin configuration.

```
self.testPrint = function(wMult, dMult) {
    wEffective = self.bedWidth() - 2* self.edgeOffset()
    dEffective = self.bedDepth() - 2* self.edgeOffset()
    xPos = 1.0*self.edgeOffset() + (wMult*wEffective);
    yPos = 1.0*self.edgeOffset() + (dMult*dEffective);
```
[change]
```
   code = [
      "G1 Z5 F2000",
      "G1"+" X" + xPos + " Y" + yPos + " F" + self.feedrate(),
      "G1 Z0.1 F1200"
    ]
```
[/change]
```
    OctoPrint.control.sendGcode(code);
}
```

I've done the above on my system. Not sure how to do the settings page stuff though, sorry. Otherwise I would have PR'd.

Have a great evening/day ... oh heck ... have a great LIFE! :-)

Bryan.

**Comment by ghost** [comment]
+1

**Comment by madmax2** [comment]
does this code work?

how to add it?

**Comment by gruvin** [comment]
2017?! Time this got put to sleep. 😄
