### ISSUE TITLE
Unit error in the interface

### ISSUE THREAD

**Issue by target888** [Peaches491/OctoPrint-Touchtest#15]
The unit for the speed is incorrect. On line 10 in "touchtest_sidebar.jinja2" the unit is in mm/min but listed as mm/sec

The feedrate that is taken from that input and used in the G0 code has the unit of mm/min. The text of the button should be change or the gcode should use the value multiplied by 60  with a change in the default value.

**Comment by luizmotta** [comment]
Fixed in c273eef3ab87524b854922bdd10a9f9936a2436c, thanks for pointing it out!
