### ISSUE TITLE
Wont uninstall 

### ISSUE THREAD

**Issue by user100000** [Peaches491/OctoPrint-Touchtest#17]
octoprint Version 1.3.6

Due the already reported locations of bed and no apparent way to reverse bed direction - attempted  to uninstall via plugin manger ,

Upon reboot  plugin gone from manager list but still installs itself in the interface.

**Comment by fritzw** [comment]
Can't confirm that. I just uninstalled it and it disappeared from the sidebar after restarting the server and reloading the UI it was gone.

**Comment by luizmotta** [comment]
Can't confirm here as well. I will close this issue, please open again if it's still happening.
