### ISSUE TITLE
Causes a TERRIBLE grinding sound when trying to home

### ISSUE THREAD

**Issue by NovaViper** [Peaches491/OctoPrint-Touchtest#20]
For some strange reason, whenever I try to use the plugin, my printer creates this SERIOUSLY loud grinding sound, even though I got the printer homed already. I have an Ender 3

**Comment by sjasonsmith** [comment]
I just encountered the same thing. Make sure you home using the normal Octoprint button before using the Touchtest home button. It seems that it does not home the XY access before executing moves, which can crash into the far side of the printer.

**Comment by tablatronix** [comment]
I am not using this ever again, thing going flying into physical limits of the printer

**Comment by tablatronix** [comment]
I looked into this, it looks like this is some kind of octoprint limitation, not sure why plugins cannot home or check that printer was homed first, but other plugins have the same issue.

**Comment by NovaViper** [comment]
If that's the case, then the plugin should be able to tell the printer to home first, then run through the test

**Comment by luizmotta** [comment]
Thanks for the suggestion, auto-homing has been implemented in the latest version. Please update.
