### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by fritzw** [Peaches491/OctoPrint-Touchtest#23]
Hey @Peaches491, are you still interested in maintaining this? It's a nice plugin that could be improved (judging by the issue tracker and pull requests), so it would be sad to see it abandoned.

In case you are interested I'd like to offer my help.

**Comment by luizmotta** [comment]
Hi @Peaches491, I'm a user of your plugin and would be glad to continue maintaining it. If you agree, please transfer the repository to me and I'll take care of the rest.

**Comment by Peaches491** [comment]
Hello @fritzw and @luizmotta! Thank you for reaching out about working on this plugin!
I'd be happy to add you both as authorized contributors, and would welcome any help you can offer.

**Comment by luizmotta** [comment]
Hi Daniel,

Thank you for adding me as contributor, I'll be happy to help. I had
incorporated some changes suggested by other users in my own branch and
have now created a pull request to add them to your master. I have tested
the changes and they are working fine in my setup. Would you like to take a
look before merging them or can I do it myself?

Best wishes,

Luiz Motta
