### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by Hoverhead** [Peaches491/OctoPrint-Touchtest#24]
Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).

**Comment by yn1v** [comment]
I also would like to have the update to python 3 for this plugin.

**Comment by jneilliii** [comment]
My Bed Leveling Wizard plugin is Python 3 compatible and you guys might find it similar in nature to this one.
