### ISSUE TITLE
Control Panel is disabled

### ISSUE THREAD

**Issue by TylonHH** [Peaches491/OctoPrint-Touchtest#3]
Hi,
my Panel is still disabled. I installed it, configured it, rebootet the Raspberry, but no luck.
When I check the html source code, I see a disabled="" tag. When I remove this I can use your plugin.
So why is it disabled?

**Comment by jeepin95** [comment]
I have the same issue in both Chrome and Firefox. I just tried changing line 18 from touchtest.js to replace self.isOperational = ko.observable(undefined); with self.isOperational = ko.observable(true); and that seems to work for all of the buttons. I'm not exactly sure what was supposed to set that to true though.

**Comment by nickm324** [comment]
same here, panel is disabled.

**Comment by luizmotta** [comment]
Just for the records, this has been fixed with commit #59eba7f
