### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by kennethjiang** [Peaches491/OctoPrint-Touchtest#7]
Thank you for your awesome plugin. It has made things a lot easier for me.

However somehow it stopped working recently. Javascript console shows this error:

`Uncaught ReferenceError: wEffective is not defined`

Screenshot attached.

I'm on OctoPrint 1.3.4. Touch Test plugin 0.1.1.

<img width="1044" alt="screen shot 2017-06-22 at 7 09 32 am" src="https://user-images.githubusercontent.com/779786/27438418-0a8a3cc0-571a-11e7-9298-85bfba80414f.png">

**Comment by luizmotta** [comment]
Is this still an issue? I can't seem to reproduce it but the problem may be installation-specific.

**Comment by kennethjiang** [comment]
I'm not sure. I have been using my own repo. 

Are you maintaining this repo now? @luizmotta

**Comment by luizmotta** [comment]
Yes, the creator has recently added me as a collaborator to this project.
If you'd like to merge something, let me know.

**Comment by kennethjiang** [comment]
I don't think it'll hurt to merge #9. It just made the code to conform better with the modern javascript specs.

**Comment by luizmotta** [comment]
Right, it was just a matter of correctly declaring the variables. Thanks for pointing it out!
